services:
  rn-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swifty-companion
    env_file:
      - ./companion/.env       # dev environment
    volumes:
      - ./companion:/app       # mount project
      - /app/node_modules      # cache node_modules
      - ./companion/.env:/app/.env
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    stdin_open: true
    tty: true
